### ISSUE TITLE
CreatePlayer should use provided token

### ISSUE THREAD

**Issue by likesmusik** [monsieur-x/server#31]
Currently a new token is generated everytime a new player is created.
If the request provides a token, the server should try to reuse it, in case the server finds a matching entry in the database.

**Comment by nstaeger** [comment]
Do not use the create-method when you have a token. You can double check if your token is valid by using `/user/myself`

**Comment by likesmusik** [comment]
This will do for now and has a better seperation of functionality, but might require an extra call (`myself`  + `createPlayer`). We could think about having a convience call like `login`.
The issue can be closed from my side.
